### ISSUE TITLE
State of the field in JOSS paper

### ISSUE THREAD

**Issue by mscroggs** [walkandthinker/AsFem#64]
There is not very much discussion of how AsFem compares to other finite element libraries in the JOSS paper. Libraries that you could mention include:

- FEniCS: [website](https://fenicsproject.org/), [GitHub repos](https://github.com/FEniCS), [paper](https://doi.org/10.11588/ans.2015.100.20553)
- MFEM: [website](https://mfem.org/), [GitHub repo](https://github.com/mfem/mfem/), [paper](https://doi.org/10.1016/j.camwa.2020.06.009)
- deal.ii: [website](https://www.dealii.org/), [GitHub repo](https://github.com/dealii/dealii), [paper](https://doi.org/10.1515/jnma-2021-0081)
- DUNE: [website](https://www.dune-project.org/), [GitHub repos](https://github.com/dune-project), [paper](https://doi.org/10.1016/j.camwa.2020.06.007)
- FreeFEM: [website](https://freefem.org/), [GitHub repos](https://github.com/FreeFem)

**Comment by vijaysm** [comment]
I'd like to second this comment as a reviewer. There are a lot of very successful and tested, general-purpose FEM libraries out there. I fail to see a proper motivation in the JOSS paper on why there was a need to create a new one, instead of using the capabilities in the ones that @mscroggs has listed above. I'd probably also add [libMesh](https://github.com/libMesh/libmesh) and [MoFEM](http://mofem.eng.gla.ac.uk/mofem/html/) to that list as well given the wide variety of applications where they have been used.

**Comment by yangbai90** [comment]
Dear @mscroggs and @vijaysm , thanks for the comments, I have added the statement for the comparsion.

**Comment by vijaysm** [comment]
The manuscript reads much better now in the statement of need section.
